version: "3.1"
services:

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: shalgham
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
